title:in search of a theorem
description: 
author: "Andrew Kitchin"
url: "https://andrewpkitchin.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  
# Collections settings to override permalinks
collections:
  posts:
    output: true
    permalink: /:title.html
    
# Default permalink structure
permalink: /:title.html

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
