title: in search of a theorem
description: A mathematics and theoretical computer science blog
author: "Andrew Kitchin"
url: "https://andrewpkitchin.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  
# Custom permalink structure without categories
permalink: /:year/:month/:day/:title.html

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
