title: in search of a theorem
description: A mathematics and theoretical computer science blog
author: "Andrew Kitchin"
baseurl: "" # Root path for user.github.io repository
url: "https://andrewpkitchin.github.io" # GitHub Pages URL

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Theme settings
header_pages:
  - about.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git